int cobra_mode(void);
void toggle_cobra_mode(void);
int cobra_stage(void);
void toggle_cobra_stage(void);
int rebug_mode(void);
void toggle_rebug_mode(void);
int normal_mode(void);
void toggle_normal_mode(void);
bool boot_mode(void);
bool debug_mode(void);
bool spe_mode(void);
bool load_ckernel(void);
bool load_dkernel(void);
void patch_dkernel(void);
void patch_ccapi(void);
void unpatch_ccapi(void);
int load_prx(void);
// void run_self(void);
void debugsettings_mode(void);
int toggle_bootplugins(void);
int toggle_sm(void);
int dump_eeprom(void);
// int read_eeprom(void);
int write_eeprom(void);
// int write_eeprom(uint64_t offset, uint8_t value);
void bootmem_toggle(void);
void cu_toggle(void);
